### ISSUE TITLE
.

### ISSUE THREAD

**Issue by dc932dc** [skyreeves/friends#4]

**Comment by skyreeves** [comment]
你的链接失效了，空了修改一下

**Comment by cyolc932** [comment]
> 你的链接失效了，空了修改一下

之前走vercel和netfly 今天全站切换到github.io了，dns解析可能要缓存，过几天应该就没事了，我刚刚访问A记录值是可以国内直连的，您看看可以连接不

**Comment by skyreeves** [comment]
嗯，是dns缓存的问题~
